#!/usr/bin/env python3
"""
Script để convert cookies từ browser sang format Netscape cookies.txt

Cách sử dụng:
1. Mở Chrome DevTools (F12) → Application → Cookies → https://www.youtube.com
2. Copy cookies dưới dạng JSON hoặc nhập thủ công
3. Chạy script này để tạo cookies.txt
"""

import json
import sys
from datetime import datetime, timedelta
from typing import List, Dict, Any


def create_netscape_cookie(
    domain: str,
    name: str,
    value: str,
    path: str = "/",
    secure: bool = False,
    expiration_days: int = 365
) -> str:
    """Tạo một dòng cookie theo format Netscape"""
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    secure_str = "TRUE" if secure else "FALSE"
    expiration = int((datetime.now() + timedelta(days=expiration_days)).timestamp())
    
    return f"{domain}\t{include_subdomains}\t{path}\t{secure_str}\t{expiration}\t{name}\t{value}"


def convert_from_json(cookies_json: List[Dict[str, Any]]) -> str:
    """Convert cookies từ JSON format sang Netscape format"""
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by convert_cookies.py",
        ""
    ]
    
    for cookie in cookies_json:
        domain = cookie.get("domain", "")
        name = cookie.get("name", "")
        value = cookie.get("value", "")
        path = cookie.get("path", "/")
        secure = cookie.get("secure", False)
        
        # Get expiration date
        if "expirationDate" in cookie:
            expiration = int(cookie["expirationDate"])
        else:
            # Default to 1 year from now
            expiration = int((datetime.now() + timedelta(days=365)).timestamp())
        
        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        secure_str = "TRUE" if secure else "FALSE"
        
        line = f"{domain}\t{include_subdomains}\t{path}\t{secure_str}\t{expiration}\t{name}\t{value}"
        lines.append(line)
    
    return "\n".join(lines)


def interactive_mode():
    """Interactive mode để nhập cookies thủ công"""
    print("=" * 60)
    print("YouTube Cookies Converter")
    print("=" * 60)
    print("\nNhập cookies từ Chrome DevTools:")
    print("1. Mở Chrome DevTools (F12)")
    print("2. Vào Application → Cookies → https://www.youtube.com")
    print("3. Copy các cookies quan trọng\n")
    
    cookies = []
    
    # Cookies quan trọng nhất
    important_cookies = [
        "VISITOR_INFO1_LIVE",
        "YSC",
        "PREF",
        "LOGIN_INFO",
        "__Secure-3PSID",
        "__Secure-3PAPISID",
    ]
    
    print("Nhập các cookies (để trống để kết thúc):")
    print("Format: domain|name|value|path|secure|expiration_days")
    print("Ví dụ: .youtube.com|VISITOR_INFO1_LIVE|abc123...|/|false|365")
    print("Hoặc chỉ nhập: name|value (sẽ dùng defaults)\n")
    
    while True:
        cookie_input = input("Cookie (hoặc Enter để kết thúc): ").strip()
        if not cookie_input:
            break
        
        try:
            parts = cookie_input.split("|")
            
            if len(parts) == 2:
                # Chỉ có name và value, dùng defaults
                name, value = parts
                domain = ".youtube.com"
                path = "/"
                secure = False
                expiration_days = 365
            elif len(parts) >= 3:
                name = parts[1]
                value = parts[2]
                domain = parts[0] if len(parts) > 0 else ".youtube.com"
                path = parts[3] if len(parts) > 3 else "/"
                secure = parts[4].lower() == "true" if len(parts) > 4 else False
                expiration_days = int(parts[5]) if len(parts) > 5 else 365
            else:
                print("❌ Format không đúng. Bỏ qua...")
                continue
            
            cookies.append({
                "domain": domain,
                "name": name,
                "value": value,
                "path": path,
                "secure": secure,
                "expirationDate": int((datetime.now() + timedelta(days=expiration_days)).timestamp())
            })
            
            print(f"✅ Đã thêm cookie: {name}")
            
        except Exception as e:
            print(f"❌ Lỗi: {e}. Bỏ qua...")
    
    if not cookies:
        print("\n❌ Không có cookies nào được nhập!")
        return
    
    # Generate file
    output = convert_from_json(cookies)
    
    # Save to file
    output_file = "cookies.txt"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(output)
    
    print(f"\n✅ Đã tạo file: {output_file}")
    print(f"📝 Tổng số cookies: {len(cookies)}")
    print(f"\n📋 Preview (10 dòng đầu):")
    print("-" * 60)
    for line in output.split("\n")[:10]:
        print(line)
    if len(output.split("\n")) > 10:
        print("...")
    print("-" * 60)
    
    print("\n💡 Bước tiếp theo:")
    print("1. Kiểm tra file cookies.txt")
    print("2. Encode: cat cookies.txt | base64")
    print("3. Set COOKIES_BASE64 trên Cloud Run")


def json_mode(json_file: str):
    """Convert từ JSON file"""
    try:
        with open(json_file, "r", encoding="utf-8") as f:
            cookies = json.load(f)
        
        if isinstance(cookies, dict) and "cookies" in cookies:
            cookies = cookies["cookies"]
        
        output = convert_from_json(cookies)
        
        output_file = "cookies.txt"
        with open(output_file, "w", encoding="utf-8") as f:
            f.write(output)
        
        print(f"✅ Đã convert {len(cookies)} cookies từ {json_file} → {output_file}")
        
    except Exception as e:
        print(f"❌ Lỗi: {e}")
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        # JSON file mode
        json_mode(sys.argv[1])
    else:
        # Interactive mode
        interactive_mode()


