import { serve } from 'https://deno.land/std@0.224.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.1'

type RapidApiTranscriptItem = {
  title?: string
  description?: string
  availableLangs?: string[]
  lengthInSeconds?: string
  thumbnails?: Array<{ url: string; width: number; height: number }>
  transcription?: Array<{
    subtitle: string
    start: number
    dur: number
  }>
  transcriptionAsText?: string
}

const RAPIDAPI_BASE = 'https://youtube-transcriptor.p.rapidapi.com'
const NO_CAPTION_ERROR = 'Video này không có caption'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY')
}

const supabaseAdmin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: {
    persistSession: false,
  },
})

const fetchTranscriptFromRapidApi = async (videoId: string, apiKey: string) => {
  const url = `${RAPIDAPI_BASE}/transcript?video_id=${encodeURIComponent(videoId)}`
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'x-rapidapi-key': apiKey,
      'x-rapidapi-host': 'youtube-transcriptor.p.rapidapi.com',
    },
  })

  if (!response.ok) {
    if (response.status === 404) {
      throw new Error(NO_CAPTION_ERROR)
    }
    throw new Error(`RapidAPI request failed (${response.status})`)
  }

  const payload = (await response.json()) as RapidApiTranscriptItem[]
  if (!Array.isArray(payload) || payload.length === 0) {
    throw new Error(NO_CAPTION_ERROR)
  }

  const firstItem = payload[0]
  if (!firstItem.transcriptionAsText || !firstItem.transcriptionAsText.trim()) {
    throw new Error(NO_CAPTION_ERROR)
  }

  return {
    transcript: firstItem.transcriptionAsText,
    language: firstItem.availableLangs?.[0] ?? null,
    isAutoGenerated: null as boolean | null,
    raw: firstItem,
  }
}

const chunkArray = <T,>(items: T[], size: number) => {
  const chunks: T[][] = []
  for (let i = 0; i < items.length; i += size) {
    chunks.push(items.slice(i, i + size))
  }
  return chunks
}

const jsonResponse = (status: number, body: Record<string, unknown>) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...corsHeaders },
  })

serve(async (request) => {
  try {
    if (request.method === 'OPTIONS') {
      return new Response('ok', { headers: corsHeaders })
    }

    if (request.method !== 'POST') {
      return jsonResponse(405, { error: 'Method not allowed' })
    }

    const apiKey = Deno.env.get('RAPIDAPI_KEY')
    if (!apiKey) {
      console.error('Missing RAPIDAPI_KEY env')
      return jsonResponse(500, { error: 'Server misconfiguration' })
    }

    const authHeader = request.headers.get('Authorization') ?? ''
    const accessToken = authHeader.replace('Bearer ', '').trim()
    if (!accessToken) {
      return jsonResponse(401, { error: 'Unauthorized' })
    }

    const { data: authData, error: authError } = await supabaseAdmin.auth.getUser(accessToken)
    if (authError || !authData?.user) {
      console.error('Failed to verify user', authError)
      return jsonResponse(401, { error: 'Unauthorized' })
    }

    const ownerId = authData.user.id

    const { videoId } = (await request.json().catch(() => ({}))) as { videoId?: string }
    if (!videoId || !/^[\w-]{6,}$/.test(videoId)) {
      return jsonResponse(400, { error: 'Invalid videoId' })
    }

    const result = await fetchTranscriptFromRapidApi(videoId, apiKey)

    const rapidItem = result.raw
    const videoPayload = {
      owner_id: ownerId,
      youtube_video_id: videoId,
      title: rapidItem.title ?? null,
      channel_name: null as string | null,
      thumbnail_url: rapidItem.thumbnails?.[rapidItem.thumbnails.length - 1]?.url ?? null,
      duration_seconds: rapidItem.lengthInSeconds ? Number(rapidItem.lengthInSeconds) : null,
      transcript: {
        provider: 'rapidapi-youtube-transcriptor',
        text: result.transcript,
        segments: rapidItem.transcription ?? [],
        fetched_at: new Date().toISOString(),
      },
      ai_metadata: {
        provider: 'rapidapi-youtube-transcriptor',
        description: rapidItem.description,
        available_langs: rapidItem.availableLangs ?? [],
      },
    }

    const { data: videoRecord, error: videoError } = await supabaseAdmin
      .from('videos')
      .upsert(videoPayload, { onConflict: 'owner_id,youtube_video_id' })
      .select('id, owner_id')
      .single()

    if (videoError || !videoRecord) {
      console.error('Failed to upsert video', videoError)
      throw new Error('Không thể lưu video vào hệ thống')
    }

    const rawSegments = rapidItem.transcription ?? []
    await supabaseAdmin.from('reading_segments').delete().eq('video_id', videoRecord.id)
    if (rawSegments.length > 0) {
      const segmentsPayload = rawSegments
        .filter((segment) => segment.subtitle?.trim().length)
        .map((segment, index) => {
          const startsAtMs =
            typeof segment.start === 'number' ? Math.round(segment.start * 1000) : null
          const endsAtMs =
            typeof segment.start === 'number' && typeof segment.dur === 'number'
              ? Math.round((segment.start + segment.dur) * 1000)
              : null

          return {
            video_id: videoRecord.id,
            segment_index: index,
            starts_at_ms: startsAtMs,
            ends_at_ms: endsAtMs,
            original_text: segment.subtitle,
            translated_text: null,
          }
        })

      for (const chunk of chunkArray(segmentsPayload, 500)) {
        if (chunk.length === 0) continue
        const { error: insertError } = await supabaseAdmin.from('reading_segments').insert(chunk)
        if (insertError) {
          console.error('Failed to insert reading segments chunk', insertError)
          throw new Error('Không thể lưu transcript vào hệ thống')
        }
      }
    }

    const { data: existingSession, error: sessionFetchError } = await supabaseAdmin
      .from('study_sessions')
      .select('id, status')
      .eq('owner_id', ownerId)
      .eq('video_id', videoRecord.id)
      .maybeSingle()

    if (sessionFetchError) {
      console.error('Failed to fetch study session', sessionFetchError)
      throw new Error('Không thể truy cập phiên học')
    }

    let sessionId: string

    if (existingSession) {
      const { error: sessionUpdateError } = await supabaseAdmin
        .from('study_sessions')
        .update({
          status: 'ready',
          last_opened_at: new Date().toISOString(),
        })
        .eq('id', existingSession.id)

      if (sessionUpdateError) {
        console.error('Failed to update existing session', sessionUpdateError)
        throw new Error('Không thể cập nhật phiên học')
      }

      sessionId = existingSession.id
    } else {
      const { data: newSession, error: sessionInsertError } = await supabaseAdmin
        .from('study_sessions')
        .insert({
          owner_id: ownerId,
          video_id: videoRecord.id,
          status: 'ready',
          reading_progress: 0,
          dictation_completed: 0,
        })
        .select('id')
        .single()

      if (sessionInsertError || !newSession) {
        console.error('Failed to create study session', sessionInsertError)
        throw new Error('Không thể tạo phiên học mới')
      }

      sessionId = newSession.id
    }

    return jsonResponse(200, {
      transcript: result.transcript,
      language: result.language,
      isAutoGenerated: result.isAutoGenerated,
      videoUuid: videoRecord.id,
      sessionId,
      youtubeVideoId: videoId,
    })
  } catch (error) {
    console.error('fetch-youtube-caption error', error)
    const message = error instanceof Error ? error.message : 'Unexpected error'
    const isNoCaption = message.includes(NO_CAPTION_ERROR)
    return jsonResponse(isNoCaption ? 404 : 500, {
      error: isNoCaption ? NO_CAPTION_ERROR : 'Không thể lấy transcript, vui lòng thử lại.',
      details: message,
    })
  }
})

